// Generated by https://quicktype.io

export interface RankingResponse {
  id:        string;
  url:       string;
  name:      string;
  beginning: string;
  end:       string;
  season:    Season;
  scores:    Score[];
}

export interface Score {
  id: string;
  rank: number;
  score: number;
  penalty: number;
  competitor: Competitor;
}

export interface Competitor {
  id: string;
  userName: string;
  imageUrl: string;
  fullName: null;
  socialLink: null;
}

export interface Season {
  id: string;
  name: string;
  beginning: string;
  end: string;
  rankings: Ranking[];
}

export interface Ranking {
  id: string;
  url: string;
  date: string;
}
