// Generated by https://quicktype.io

export interface SeasonByIdResponse {
    id:        string;
    name:      string;
    beginning: string;
    end:       string;
    rankings?:  Ranking[];
}// Generated by https://quicktype.io

export interface SeasonResponse {
    id:                string;
    name:              string;
    beginning:         string;
    end:               string;
    numberCompetitors: number;
    numberChanllenges: number;
}


export interface Ranking {
    id:         string;
    url:        string;
    created_at: string;
    scores:     Score[];
}

export interface Score {
    id:      string;
    rank:    number;
    score:   number;
    penalty: number;
}

export interface SeasonProps {
    season: SeasonByIdResponse
}

export interface SeasonProps {
    seasonData: SeasonResponse
    globalRanking: RakingGlobal[]
}

export interface SeasonParams {
    seasonId: string
}// Generated by https://quicktype.io

export interface RakingGlobal {
    rank:       number;
    score:      number;
    penalty:    number;
    competitor: Competitor;
}

export interface Competitor {
    id:         string;
    userName:   string;
    imageUrl:   string;
    fullName:   null;
    socialLink: null;
}


export interface Params {
    params: SeasonParams
}

