// Generated by https://quicktype.io

export interface SeasonsResponse {
    id:        string;
    name:      string;
    beginning: string;
    end:       string;
    rankings?:  Ranking[];
}

export interface Ranking {
    id:         string;
    url:        string;
    created_at: string;
    scores:     Score[];
}

export interface Score {
    id:         string;
    rank:       number;
    score:      number;
    penalty:    number;
    competitor: Competitor;
}

export interface Competitor {
    id:         string;
    userName:   string;
    imageUrl:   string;
    fullName:   null;
    socialLink: null;
}

// Generated by https://quicktype.io

export interface SeasonCreatedResponse {
    season: Season;
    msg:    string;
}

export interface Season {
    name:      string;
    beginning: string;
    end:       string;
    id:        string;
}
